### PR TITLE
checkpoint.JBPM-5490: Upgrade to lienzo 2.0.287-RELEASE.

### PR DESCRIPTION
**Pull request by romartin**
Hey @manstis @psiroky 

This is the lienzo versions upgrade for uberfire too. See [this related PR](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/433).

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
oops sorry bad title! lemme fix it

**Comment by romartin** [comment]
commit message fixed.

**Comment by manstis** [comment]
ok to test

**Comment by manstis** [comment]
@ederign @porcelli @psiroky Could somebody please merge?

**Pull request merged**
