### PR TITLE
JBPM-6203 - Remove view mode preference

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by ederign** [comment]
@mbiarnes @psiroky do you guys have an idea of why we are getting this error on branch 1.3.x of appformer? 12:49:01 Unexpected error while executing the UpstreamReposBuilder! Unknown branch '1.3.x'! Make sure the plugin is aware of the specified branch.
12:49:01 java.lang.IllegalArgumentException: Unknown branch '1.3.x'! Make sure the plugin is aware of the specified branch.

**Comment by cristianonicolai** [comment]
@ederign `org.uberfire.ext.metadata.io.IOServiceIndexedGitImplTest` seems to be failing randomly, could you take a look?

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by ederign** [comment]
@cristianonicolai sure. I'll take a look.

**Comment by ederign** [comment]
Jenkins please execute full downstream build.

**Pull request merged**
