### PR TITLE
[AF-544] Allow close a expanded dock via API

### PR DESCRIPTION
**Pull request by ederign**
[AF-556] Docks API should receive calls even if the docks are not ready.

### CODE REVIEW

**Comment by ederign** [comment]
Don't merge this yet. Just for API review (before touching all the repos)

**Comment by porcelli** [comment]
it look ok, but i'm not sure about : enable/disable method names. I'd prefer:
- expand/collapse (and I'd add a toggle method too)
- show/hide

**Comment by ederign** [comment]
@porcelli PR (and API) updated.

Child: https://github.com/kiegroup/kie-wb-common/pull/951

**Comment by ederign** [comment]
jenkins retest this

**Comment by ederign** [comment]
jenkins retest this

**Pull request merged**
