### PR TITLE
JBPM-5862: Stunner - Diagram tree explorer improvements.

### PR DESCRIPTION
**Pull request by alepintus**
This is an improvement of the uberfire tree used by stunner. [See this ticket](https://issues.jboss.org/browse/JBPM-5862).
Thanks

### CODE REVIEW

**Comment by romartin** [comment]
ok to test

**Comment by alepintus** [comment]
New commit added for fixing tests. 
Thanks

**Comment by ederign** [comment]
@romartin can you please take a look on this?

**Comment by romartin** [comment]
@ederign @porcelli  sure looking right now.

**Pull request merged**
