### PR TITLE
AF-324, AF-475, AF-476: [Security management] Fixed issues when creating/deleting users and groups

### PR DESCRIPTION
**Pull request by romartin**
Hey @ederign @tomasdavidorg @manstis 

These are some critical bug fixes for next release about users managements stuff:
- [AF-324](https://issues.jboss.org/browse/AF-324)  It is not possible to delete created user
- [AF-475](https://issues.jboss.org/browse/AF-475) User with space in name cannot be created
- [AF-476](https://issues.jboss.org/browse/AF-476) Exception when creating a group

Thanks guys!

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
oh @manstis @tomasdavidorg  just realized @ederign is not around this week... and as these tickets are important for LA... please could you do the review? or lemme know who can I ask for? In addition I guess it  should be cherry-picked to the `1.3.x` branch too, right?
Thanks in advance!!!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
hey @psiroky , please need some help, some clues... there is no way to make the full downstream build to work on some tickets, it's complaining at some point when trying to use the github api.... but I see other PRs on green.. can it be due to the branch name? can I do something to make this compile? 

Sorry I need a few tickets urgently merged for next release, but there is no way to make the full downstream build to work :( The ticket are:
- https://github.com/AppFormer/uberfire/pull/851
- https://github.com/AppFormer/uberfire/pull/856
- https://github.com/AppFormer/uberfire/pull/857

Thanks in advance!!

**Comment by psiroky** [comment]
@romartin looks like a GitHub API is not responding correctly. I am afraid I can't do much with that.

**Comment by romartin** [comment]
ahhh ok, makes sense  @psiroky thanks. Will keep trying....

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
green!! :+1:

**Pull request merged**
