### PR TITLE
[1.2.x] GUVNOR-3351: Make validation dialog more readable

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-3351

This is the corollary of https://github.com/AppFormer/uberfire/pull/783 for 7.2.x

Branch name is ```-7.2.x``` so Jenkins can build related PRs successfully.

(cherry picked from commit c7b0f6279d981f67924f29907f20a16bbdf289c0)

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:
- https://github.com/AppFormer/uberfire/pull/790
- https://github.com/kiegroup/kie-wb-common/pull/1012

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@mariofusco @mswiderski (anybody!) Is [this](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/uberfire-downstream-pullrequests-1.2.x/5/testReport/org.kie.karaf.itest/KieDMNKarafIntegrationTest/testDMNbasic/) a known intermittent test failure or does somebody need to take a look?

**Comment by mswiderski** [comment]
@manstis I believe it was already fixed yesterday by @mariofusco

**Comment by manstis** [comment]
@mswiderski Great.. May the CI Gods pass my subsequent request.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Pull request merged**
