### PR TITLE
[1.3.x] GUVNOR-3198: Increase RestrictedMousePanMediator coverage

### PR DESCRIPTION
**Pull request by jomarko**
This is cherry-pick of #815 . @karreiro @manstis, please have a look when you have  moment.

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
