### PR TITLE
AF-593+: Move dashbuilder to uberfire.

### PR DESCRIPTION
**Pull request by mbarkley**

### CODE REVIEW

**Comment by mbarkley** [comment]
Related:
https://github.com/kiegroup/kie-soup/pull/13
https://github.com/AppFormer/uberfire/pull/898
https://github.com/dashbuilder/dashbuilder/pull/396
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/599
https://github.com/kiegroup/jbpm/pull/1060
https://github.com/kiegroup/droolsjbpm-integration/pull/1260
https://github.com/kiegroup/kie-wb-common/pull/1279
https://github.com/kiegroup/drools-wb/pull/701
https://github.com/kiegroup/jbpm-wb/pull/938
https://github.com/kiegroup/optaplanner-wb/pull/237
https://github.com/kiegroup/kie-wb-distributions/pull/650

**Comment by mbarkley** [comment]
This PR moves the remaining dashbuilder modules to uberfire. It does not rename them any source code or even the artifact names because soon we will be moving all of uberfire to a new repository and renaming it to appformer.

The dashbuilder artifacts do have a new version (matching uberfire 2.0.0-SNASPHOT). Additionally the dashbuilder-bom and third-party dependency management have been merged into the uberfire-bom and uberfire-parent respectively.

**Comment by mbarkley** [comment]
@ederign @dgutierr @psiroky @mbiarnes I would appreciate if any of you are able to review the uberfire-parent POM file changes. I had to merge most of the configuration from dashbuilder-parent into uberfire-parent. Specifically dependencyManagement, pluginManagement, and version properties.

**Comment by ederign** [comment]
@mbarkley this is still on your radar? Should I review this? If so, how we will sync with new modifications of dashbuilder?

**Comment by psiroky** [comment]
Any chance to preserve the history? I think it may be beneficial.

**Comment by mbarkley** [comment]
This set of PRs is blocked by the ElasticSearch version upgrade. Since this has taken much longer to be ready than expected, I am going to close all these PRs and will start this over again with all the newest changes.

**Pull request closed without merging**
