### PR TITLE
Layout editor fixes

### PR DESCRIPTION
**Pull request by dgutierr**
It fixes a couple of bugs reported by QE.

@kkufova @ederign mind to review please?

### CODE REVIEW

**Comment by kkufova** [comment]
jenkins execute full downstream build

**Comment by kkufova** [comment]
jenkins execute full downstream build

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by kkufova** [comment]
@dgutierr, everything works fine, however, I noticed that if you create a page with the name of an already existing screen, both of these pages are then listed -- for example when adding a page to a tree in the Navigation panel -- and you cannot tell which is which. Would it be possible to deal with this somehow? Maybe make it impossible to create pages with such names, or always automatically add some "note" to their name in the places where the problem occurs, such as `Home (custom)` to make it clear. WDYT?

screenshot from 2017-11-13 09-46-26

**Comment by dgutierr** [comment]
@kkufova good point. As you point out, having a mechanism to differentiate which page has been created by the user would be great. "Home (custom)" could be an option. It is not that critical though, as users can always, rename their pages to avoid clashing with existing hard coded pages. Yet, looking at the code, it is not as simple as would seem to implement it.

**Comment by kkufova** [comment]
@dgutierr, okay, thanks for such quick reply! So do we want to implement this as a part of this pull request or create a Jira for this issue and a new PR?

**Comment by dgutierr** [comment]
@kkufova I'd rather file another JIRA. Cheers!

**Comment by kkufova** [comment]
@dgutierr, done: https://issues.jboss.org/browse/AF-906

**Comment by ederign** [comment]
@dgutierr thanks for handling this!

**Comment by manstis** [comment]
@dgutierr Has this broken Dashbuilder?

I could not compile ```drools-wb``` due to:
```
[ERROR] Errors in 'jar:file:/home/manstis/.m2/repository/org/dashbuilder/dashbuilder-common-client/1.1.0-SNAPSHOT/dashbuilder-common-client-1.1.0-SNAPSHOT-sources.jar!/org/dashbuilder/common/client/editor/list/DropDownEditor.java'
[INFO]          [ERROR] Line 156: The method setSelectedItem(String, String) in the type LiveSearchDropDown is not applicable for the arguments (String)
[INFO]          [ERROR] Line 118: The method getSelectedItem() is undefined for the type LiveSearchDropDown
[INFO]          [ERROR] Line 207: The method setSelectedItem(String, String) in the type LiveSearchDropDown is not applicable for the arguments (String)
[INFO]          [ERROR] Line 105: The method afterSearch(LiveSearchResults) in the type LiveSearchCallback is not applicable for the arguments (List<String>)
[INFO]          [ERROR] Line 205: The method setSelectedItem(String, String) in the type LiveSearchDropDown is not applicable for the arguments (String)
[INFO]          [ERROR] Line 105: Type mismatch: cannot convert from List<String> to LiveSearchResults
```
However even fetching the latest Dashbuidler code and compiling locally gives much the same error.

**Comment by psiroky** [comment]
Per @dgutierr this commit should fix it https://github.com/dashbuilder/dashbuilder/commit/43ec2b8b5cdd9e1984bf15cbe9bc9fe746b4df21.

**Pull request merged**
