### PR TITLE
A refactor that basically decompose the old JGitUtil to a command based approach

### PR DESCRIPTION
**Pull request by porcelli**
This PR content has been staled in my local for a while (since beginning of the year) - I never managed to get back and proper finish it (decompose the existing tests to be command based as well; but the coverage of tests is still high.. not just corrected split in proper command based test).

The point to submit this PR is that @ederign is now working on Git to simplify the current clustering... so I think makes more sense to start from a better/organized codebase than force him to do it in the current JGitUtil mess.

### CODE REVIEW

**Comment by ederign** [comment]
org.kie.karaf.itest.KieSpringDependencyKarafIntegrationTest.testKieBase
org.kie.karaf.itest.KieSpringMetaInfAppContextKarafIntegrationTest.testKieBase
org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest.testJbpmRuntimeManagerWithPersistence
org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest.testJbpmRuntimeManager
org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest.testKieSession
org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest.testKieBase
org.kie.karaf.itest.SimpleKieSpringKarafIntegrationTest.testKieSessionDefaultType
org.kie.karaf.itest.blueprint.KieBlueprintDependencyKarafIntegrationTest.testKieBase
org.kie.karaf.itest.blueprint.KieBlueprintProcessDependencyKarafIntegrationTest.testKieBase
org.kie.karaf.itest.blueprint.KieBlueprintProcessDependencyKarafIntegrationTest.testStartProcess

**Comment by ederign** [comment]
screenshot 2017-07-25 18 42 21

**Comment by porcelli** [comment]
tests aren't related

**Comment by Rikkola** [comment]
Hi @porcelli 
Looks like `RepositoryVisitorTest` in guvnor also uses JGitUtil.

**Comment by Rikkola** [comment]
Or does it? Looks like my branch is the only one with this test. Investigating.

**Comment by Rikkola** [comment]
Nope, just didn't find the file with GitHub search. Here is the link.
https://github.com/kiegroup/guvnor/blob/master/guvnor-ala/guvnor-ala-build-maven/src/test/java/org/guvnor/ala/build/maven/executor/RepositoryVisitorTest.java#L46

**Comment by manstis** [comment]
And kie-wb-common is broken.

Guvnor fix : https://github.com/kiegroup/guvnor/pull/480

Massimiliano Dessì is to fix ```kie-wb-common```

Out of interest where was the full downstream build?

**Comment by psiroky** [comment]
@manstis not completely sure the question is rhetorical, so I will answer :) The downstream build is right there, failing on the very same compilation error you fixed. One thing that should be improved though is the status message. It may look like the build actually finished, with 10 tests failing. The truth is that 10 tests failed in -integration, but then the build failed in guvnor.

**Pull request merged**
