### PR TITLE
GUVNOR-3233: [Preferences] Invalid values of File exporting properties break Admin page

### PR DESCRIPTION
**Pull request by romartin**
Hey @manstis @tomasdavidorg @paulovmr 

This commit adds preferences validators for the PDF file export stuff.  Please, this ticket is important for next LA, would appreciate some feedback when you have chance., thanks in advance!!!

Notice moved from the use of `Enum`, as fields in the preferences bean,  to the use of `String`, because I was facing some issues, specially while coding in SDM, about the generated preferences beans, and because the value type for `PropertyValidator` are String's too. Anyway finally created 2 more built-in preference validators for constraining values - one for generic objects and another implementation for `Enum` types. This way the PDF file export preferences just re-use the core validator for enums for each field.

Thanks!

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by psiroky** [comment]
@romartin if the error is the same for multiple runs, that means it's likely some other issue. Not sure what could be the root cause though. Could you try to rebase the branch against the latest master?

**Comment by romartin** [comment]
Just rebased - let's see if Jenkins agrees now

**Comment by manstis** [comment]
I doubt it. He's been disagreeable today.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
Errors are not related.

**Pull request merged**
