### PR TITLE
AF-567: Create permission is not dependent on read permission

### PR DESCRIPTION
**Pull request by tomasdavidorg**

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
I have to do some checks but kie-wb-distribution build is broken.

**Comment by tomasdavidorg** [comment]
Ready for review. Thanks.

**Comment by tomasdavidorg** [comment]
You can't create already created project, so the create permission is not applicable in this case.

**Comment by tomasdavidorg** [comment]
Thanks and yes, @dgutierr or @romartin could you please have a look?

**Comment by ederign** [comment]
thanks @tomasdavidorg

**Pull request merged**
