### PR TITLE
Uberfire breadcrumbs adds extra space between navbar and perspective content

### PR DESCRIPTION
**Pull request by ederign**
@paulovmr sorry for a new PR. I did a mistake on UF-462 and uf-462 :-(

https://github.com/AppFormer/uberfire/pull/682

### CODE REVIEW

**Comment by ederign** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
@ederign Only `BatchIndexConcurrencyTest.testSingleConcurrentBatchIndexExecution` is failing now.

**Comment by ederign** [comment]
thanks @paulovmr

**Comment by manstis** [comment]
Now.... these "indexing" tests should not be failing at all these days... @porcelli moved them to Byteman and hence are no longer subject to timeouts or other subjective variables... the failures might need investigating.

**Comment by ederign** [comment]
@manstis I'll take a look on this on monday!

**Pull request merged**
