### PR TITLE
[1.4.x] AF-434: [HTML editor] Font size, Font color and Backgroud color are not working.

### PR DESCRIPTION
**Pull request by pefernan**
Copy of https://github.com/AppFormer/uberfire/pull/870

@ederign @paulovmr @jsoltes could you please take a look?

### CODE REVIEW

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Comment by jsoltes** [comment]
There is a typo in the text size - the biggest size is called xx-small, should be xx-large instead...
image

**Comment by pefernan** [comment]
@jsoltes well seen the typo. I'll fix it. 
The issue you mention on about opening the panels for link, color... That's how the Js library behaves, I tried to change it but it's been impossible.

**Comment by jsoltes** [comment]
@pefernan I see, so after the typo is fixed, +1.

**Comment by pefernan** [comment]
@jsoltes fixed thanks (also sent PR to master to fix this)

**Pull request merged**
