### PR TITLE
changed filenames and variable-names for consistency with other scripts

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
please merge together with:
https://github.com/kiegroup/kie-jenkins-scripts/pull/32
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/495
https://github.com/mbiarnes/dashbuilder/tree/changeFileNames

**Comment by ederign** [comment]
@mbiarnes could you please write a more clear commit message?

**Comment by mbiarnes** [comment]
@ederign edited a more clear commit message

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Pull request merged**
