### PR TITLE
JBPM-5542: Stunner - Properties Panel and Process Explorer are shown for incorrect asset

### PR DESCRIPTION
**Pull request by pefernan**
The idea is refreshing only the affected docks when new dock elements are added or removed.

@ederign can you take a look? Does it fit what we talked yesterday?

### CODE REVIEW

**Comment by psiroky** [comment]
@mbiarnes could you please check why the jenkins is asking for approval? This should not be needed afaik.

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Pull request closed without merging**
